-- TODO Add column price to "products" table. The column should be able to hold 2 digits after the decimal separator and only allow numeric values (separator is allowed).
-- Write the "alter table" query here
